### ISSUE TITLE
Predictive loading does not work

### ISSUE THREAD

**Issue by SergeyMell** [mgechev/ng-ml-bundled#1]
Hi there!

I've pulled your repository, connected it to my GA account and deployed: https://guess-c25f7.firebaseapp.com/main

However, no predictive module loading appeared. All modules are loaded only after I click on the link.
What am I doing wrong?

I'll attach the data, I have from google analytics
![screenshot at 05 15-43-56](https://user-images.githubusercontent.com/12133261/40976617-52475280-68d7-11e8-91e8-ffbdd73035d4.png)

**Comment by mgechev** [comment]
Hey @SergeyMell, really happy to see you decided to give it a try!

From what I see, the Guess.js runtime is not part of your main bundle. Would you share the webpack output during the build process?

**Comment by mgechev** [comment]
Btw, for comparison, you can look at https://guess-js-angular-demo.firebaseapp.com/.

Specifically, see [main.bundle.js](https://guess-js-angular-demo.firebaseapp.com/main.bundle.js).

**Comment by SergeyMell** [comment]
@mgechev, thank you for such a quick answer.
Here is my webpack build log file.
[webpack.build.log](https://github.com/mgechev/guess-js-angular-demo/files/2073817/webpack.build.log)

Actually, I've just downloaded your code and built it. Only added `ga` script into header and `ga(send)` scripts into `ngOnInit` methods in order to track user activities.

**Comment by mgechev** [comment]
Did you replace `GA` in `webpack.config.js` with your view ID?

**Comment by SergeyMell** [comment]
Sure, I did.
But that doesn't answer the question why main.bundle is missing guess.js

I was using npm 8.9.0 to install dependencies, not yarn.

**Comment by mgechev** [comment]
And you got the browser window for authentication?

![](https://blog.mgechev.com/images/intro-guess-js/guess-plugin-demo.gif)

**Comment by SergeyMell** [comment]
Yes, and raised hands after that.
However, even if I provide incorrect View ID I don't get any error messages. Debug mode (`debug: true` in plugin config) also doesn't help

**Comment by mgechev** [comment]
Btw, there's no `npm@8.9.0`. Probably that's your node version.

**Comment by mgechev** [comment]
My guess is that there's a runtime error which is masked by webpack.

**Comment by SergeyMell** [comment]
> Btw, there's no npm@8.9.0. Probably that's your node version.

Yes, you're right. node v8.9.0 (npm v5.5.1)

**Comment by SergeyMell** [comment]
> My guess is that there's a runtime error which is masked by webpack.

I there any way I can check or overcome it?

**Comment by mgechev** [comment]
The easiest would be if you can give me read-only access to the report so I can test it from my account. I'd also need the view ID. I hope this is just a test account? `mgechev@gmail.com` is my email.

**Comment by SergeyMell** [comment]
Done
View ID is 176587667

Thanks a lot for your help

**Comment by mgechev** [comment]
Everything works properly for me:

```diff
    new GuessPlugin({
-     GA: '128035004',
+     GA: '176587667',
      period: {
        startDate: new Date('2016-1-2'),
        endDate: new Date('2018-2-24')
```

Of course, I get an empty result set for this interval.

**Comment by mgechev** [comment]
@SergeyMell that's the content of my `main.bundle.js` https://gist.github.com/mgechev/74055b199270860e71929c7960a4fc79.

**Comment by SergeyMell** [comment]
Mine is extremely different
https://gist.github.com/SergeyMell/63acfab355bf87ec3941c460dbc20bf0
What version of webpack do you use?

**Comment by mgechev** [comment]
The one in `package.json`, `webpack@3.11.0`.

**Comment by mgechev** [comment]
Btw, Guess.js should work properly with webpack@4+. That's what we used for Gatsby.

**Comment by mgechev** [comment]
What's your operating system? I don't think we've tried the plugin on anything else than macOS.

**Comment by SergeyMell** [comment]
Very strange, but it seems like started to work for some reason... I just deleted the `dist` directory before running `npm run build` on more time. This time it didn't ask me for google analytics credentials but guess.js seems to be a part of `main.bundle.js` for now.

One more strange thing I noticed: When it application is loaded only `intro.module.chunk.js` is loaded (from lazy modules I mean). However, I assumed that `main.module.chunk.js` should be loaded either because it's the most likely to navigate from intro accoring to ga. 

After I start navigating to other routes other chunks are preloaded which is correct, but not for the first time. Please, see the screenshot.

<img width="891" alt="screenshot at 06 00-11-38" src="https://user-images.githubusercontent.com/12133261/41003040-4454ebf0-691e-11e8-91ad-b9b726f6e885.png">

**Comment by SergeyMell** [comment]
`Navigated to intro` and `navigated back to main` should be vise versa on screenshot:
`Navigated to main` and `navigated back to intro`. Sorry for this mistake...

**Comment by SergeyMell** [comment]
> What's your operating system? I don't think we've tried the plugin on anything else than macOS.

I have OS X El Capitan

**Comment by SergeyMell** [comment]
So, the problem seems to be solved by means of some webpack magic after deleting `dist` folder. Maybe this issue would help to figure out some artifacts with building progress. 
Thanks a lot for your help, I appreciate.

**Comment by mgechev** [comment]
Thanks for giving the plugin a try! Next a couple of weeks we'll be working on updating the API. In case you have a use case for Guess.js, I'd love to chat with you and help you be successful with it.
